apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shopware-k3s.fullname" . }}-app
  labels:
    {{- include "shopware-k3s.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "shopware-k3s.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        {{- include "shopware-k3s.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: app
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "shopware-k3s.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: shopware-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ include "shopware-k3s.fullname" . }}-env
          env:
            - name: APP_DEBUG
              value: "0"
            - name: TRUSTED_PROXIES
              value: {{ .Values.shopware.trustedProxies | quote }}
            - name: PHP_MEMORY_LIMIT
              value: "1G"
            - name: SYMFONY_TRUSTED_PROXIES
              value: {{ .Values.shopware.trustedProxies | quote }}
            - name: SYMFONY_TRUSTED_HEADERS
              value: "x-forwarded-for,x-forwarded-host,x-forwarded-proto,x-forwarded-port"
          ports:
            - name: http
              containerPort: {{ .Values.app.service.port }}
              protocol: TCP
          volumeMounts:
            - name: media
              mountPath: /var/www/html/public/media
            - name: media
              mountPath: /var/www/html/files

          startupProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30

          {{- if .Values.app.readinessProbe.enabled }}
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
          {{- end }}

          {{- if .Values.app.livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 90
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
          {{- end }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: {{ default (printf "%s-media" (include "shopware-k3s.fullname" .)) .Values.persistence.media.existingClaim }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}