{{- if .Values.ebayAdapter.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shopware-k3s.fullname" . }}-ebay-adapter
  labels:
    {{- include "shopware-k3s.labels" . | nindent 4 }}
type: Opaque
stringData:
  EBAY_CLIENT_ID: {{ .Values.ebayAdapter.clientId | quote }}
  EBAY_CLIENT_SECRET: {{ .Values.ebayAdapter.clientSecret | quote }}
  EBAY_REFRESH_TOKEN: {{ .Values.ebayAdapter.refreshToken | quote }}
  {{- if .Values.ebayAdapter.shopwareAdminApiToken }}
  SHOPWARE_ADMIN_API_TOKEN: {{ .Values.ebayAdapter.shopwareAdminApiToken | quote }}
  {{- end }}
{{- end }}

