{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shopware-k3s.fullname" . }}-mariadb
  labels:
    {{- include "shopware-k3s.labels" . | nindent 4 }}
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: {{ .Values.mariadb.rootPassword | quote }}
  MARIADB_DATABASE: {{ .Values.mariadb.database | quote }}
  MARIADB_USER: {{ .Values.mariadb.user | quote }}
  MARIADB_PASSWORD: {{ .Values.mariadb.password | quote }}
{{- end }}
