{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shopware-k3s.fullname" . }}-mariadb
  labels:
    {{- include "shopware-k3s.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      protocol: TCP
  selector:
    {{- include "shopware-k3s.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
{{- end }}
