apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shopware-k3s.fullname" . }}-env
  labels:
    {{- include "shopware-k3s.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_ENV: {{ .Values.shopware.appEnv | quote }}
  APP_URL: {{ .Values.shopware.appUrl | quote }}
  APP_SECRET: {{ .Values.shopware.appSecret | quote }}
  INSTANCE_ID: {{ .Values.shopware.instanceId | quote }}
  DATABASE_URL: {{ include "shopware-k3s.databaseUrl" . | quote }}
  {{- if .Values.redis.enabled }}
  REDIS_URL: {{ .Values.redis.url | quote }}
  {{- end }}
  MAILER_DSN: {{ .Values.shopware.mailerDsn | quote }}
