image:
  repository: ghcr.io/joachimdettbarn/shopware-runtime
  tag: "6.6.8-custom"

shopware:
  appUrl: https://shop.cloud.dettbarn.org
  appSecret: "CHANGE_ME_TO_A_LONG_RANDOM_VALUE"
  instanceId: "CHANGE_ME_TO_A_UUID"
  mailerDsn: "smtp://user:pass@smtp.example.tld:587?encryption=tls&auth_mode=login"

mariadb:
  host: mariadb.shop.svc.cluster.local
  port: 3306
  database: shopware
  user: shopware
  password: "CHANGE_ME"

redis:
  enabled: true
  url: redis://redis-master.shop.svc.cluster.local:6379/0

persistence:
  media:
    storageClass: longhorn-retain
    accessModes:
      - ReadWriteMany
    size: 20Gi

ingress:
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer-prod
  hosts:
    - host: shop.cloud.dettbarn.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: shop-cloud-dettbarn-org-tls
      hosts:
        - shop.cloud.dettbarn.org
